import type { Metadata } from 'next'
import './globals.css'
import { sahel } from '@/lib/fonts'
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/providers/modalProvider'
import { ToastProvider } from '@/providers/toastProvider'

export const metadata: Metadata = {
  title: 'داشبورد فروشگاهها',
  description: 'Generated by create next app',
}

export default function RootLayout(props: LayoutProp) {
  const { children } = props

  return (
    <ClerkProvider>
      <html lang="fa" dir='rtl'>
        <body className={`${sahel.variable} font-sahel`}>
          <ToastProvider />
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
