import type { Metadata } from 'next'
import './globals.css'
import { sahel } from '@/lib/fonts'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: LayoutProp) {
  const { children } = props
  return (
    <ClerkProvider>
      <html lang="fa" dir='rtl'>
        <body className={`${sahel.variable} font-sahel`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
